# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sun Sep 28 14:07:04 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1046, 545)
        MainWindow.setStyleSheet(_fromUtf8("QListWidget {\n"
"    border: none;\n"
"    background: transparent;\n"
"}"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.searchEdit = QtGui.QLineEdit(self.centralwidget)
        self.searchEdit.setObjectName(_fromUtf8("searchEdit"))
        self.horizontalLayout.addWidget(self.searchEdit)
        self.userLogin = QtGui.QLabel(self.centralwidget)
        self.userLogin.setObjectName(_fromUtf8("userLogin"))
        self.horizontalLayout.addWidget(self.userLogin)
        self.userIcon = QtGui.QLabel(self.centralwidget)
        self.userIcon.setMinimumSize(QtCore.QSize(30, 30))
        self.userIcon.setMaximumSize(QtCore.QSize(30, 30))
        self.userIcon.setText(_fromUtf8(""))
        self.userIcon.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/loading_black.gif")))
        self.userIcon.setObjectName(_fromUtf8("userIcon"))
        self.horizontalLayout.addWidget(self.userIcon)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalWidget_2 = QtGui.QWidget(self.centralwidget)
        self.verticalWidget_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.verticalWidget_2.setObjectName(_fromUtf8("verticalWidget_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalWidget_2)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label = QtGui.QLabel(self.verticalWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_5.addWidget(self.label)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.leftMenu = QtGui.QListWidget(self.verticalWidget_2)
        self.leftMenu.setMaximumSize(QtCore.QSize(16777215, 75))
        self.leftMenu.setObjectName(_fromUtf8("leftMenu"))
        item = QtGui.QListWidgetItem()
        self.leftMenu.addItem(item)
        item = QtGui.QListWidgetItem()
        self.leftMenu.addItem(item)
        self.horizontalLayout_6.addWidget(self.leftMenu)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.label_2 = QtGui.QLabel(self.verticalWidget_2)
        self.label_2.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_5.addWidget(self.label_2)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem1 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.leftPlaylist = QtGui.QListWidget(self.verticalWidget_2)
        self.leftPlaylist.setObjectName(_fromUtf8("leftPlaylist"))
        self.horizontalLayout_7.addWidget(self.leftPlaylist)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.horizontalLayout_4.addWidget(self.verticalWidget_2)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.shuffleLibraryButton = QtGui.QPushButton(self.centralwidget)
        self.shuffleLibraryButton.setObjectName(_fromUtf8("shuffleLibraryButton"))
        self.horizontalLayout_5.addWidget(self.shuffleLibraryButton)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.uploadMusicButton = QtGui.QPushButton(self.centralwidget)
        self.uploadMusicButton.setObjectName(_fromUtf8("uploadMusicButton"))
        self.horizontalLayout_5.addWidget(self.uploadMusicButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.allSongsPage = QtGui.QWidget()
        self.allSongsPage.setObjectName(_fromUtf8("allSongsPage"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.allSongsPage)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.allSongsTable = QtGui.QTableWidget(self.allSongsPage)
        self.allSongsTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.allSongsTable.setProperty("showDropIndicator", False)
        self.allSongsTable.setAlternatingRowColors(True)
        self.allSongsTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.allSongsTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.allSongsTable.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.allSongsTable.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.allSongsTable.setShowGrid(False)
        self.allSongsTable.setGridStyle(QtCore.Qt.NoPen)
        self.allSongsTable.setCornerButtonEnabled(False)
        self.allSongsTable.setObjectName(_fromUtf8("allSongsTable"))
        self.allSongsTable.setColumnCount(8)
        self.allSongsTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.allSongsTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.allSongsTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.allSongsTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.allSongsTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.allSongsTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.allSongsTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.allSongsTable.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.allSongsTable.setHorizontalHeaderItem(7, item)
        self.allSongsTable.horizontalHeader().setDefaultSectionSize(120)
        self.allSongsTable.horizontalHeader().setHighlightSections(False)
        self.allSongsTable.horizontalHeader().setMinimumSectionSize(50)
        self.allSongsTable.horizontalHeader().setSortIndicatorShown(True)
        self.allSongsTable.horizontalHeader().setStretchLastSection(True)
        self.allSongsTable.verticalHeader().setVisible(False)
        self.allSongsTable.verticalHeader().setHighlightSections(False)
        self.verticalLayout_6.addWidget(self.allSongsTable)
        self.stackedWidget.addWidget(self.allSongsPage)
        self.searchPage = QtGui.QWidget()
        self.searchPage.setObjectName(_fromUtf8("searchPage"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.searchPage)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.searchSongsTable = QtGui.QTableWidget(self.searchPage)
        self.searchSongsTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.searchSongsTable.setProperty("showDropIndicator", False)
        self.searchSongsTable.setAlternatingRowColors(True)
        self.searchSongsTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.searchSongsTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.searchSongsTable.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.searchSongsTable.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.searchSongsTable.setShowGrid(False)
        self.searchSongsTable.setGridStyle(QtCore.Qt.NoPen)
        self.searchSongsTable.setCornerButtonEnabled(False)
        self.searchSongsTable.setObjectName(_fromUtf8("searchSongsTable"))
        self.searchSongsTable.setColumnCount(8)
        self.searchSongsTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.searchSongsTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.searchSongsTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.searchSongsTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.searchSongsTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.searchSongsTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.searchSongsTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.searchSongsTable.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.searchSongsTable.setHorizontalHeaderItem(7, item)
        self.searchSongsTable.horizontalHeader().setDefaultSectionSize(120)
        self.searchSongsTable.horizontalHeader().setHighlightSections(False)
        self.searchSongsTable.horizontalHeader().setMinimumSectionSize(50)
        self.searchSongsTable.horizontalHeader().setSortIndicatorShown(True)
        self.searchSongsTable.horizontalHeader().setStretchLastSection(True)
        self.searchSongsTable.verticalHeader().setVisible(False)
        self.searchSongsTable.verticalHeader().setHighlightSections(False)
        self.verticalLayout_7.addWidget(self.searchSongsTable)
        self.stackedWidget.addWidget(self.searchPage)
        self.verticalLayout_4.addWidget(self.stackedWidget)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.trackIcon = QtGui.QLabel(self.centralwidget)
        self.trackIcon.setMinimumSize(QtCore.QSize(50, 50))
        self.trackIcon.setMaximumSize(QtCore.QSize(50, 50))
        self.trackIcon.setText(_fromUtf8(""))
        self.trackIcon.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/default-album-art.png")))
        self.trackIcon.setScaledContents(True)
        self.trackIcon.setObjectName(_fromUtf8("trackIcon"))
        self.horizontalLayout_2.addWidget(self.trackIcon)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.musicSeeker = QtGui.QSlider(self.centralwidget)
        self.musicSeeker.setMaximumSize(QtCore.QSize(16777215, 15))
        self.musicSeeker.setOrientation(QtCore.Qt.Horizontal)
        self.musicSeeker.setObjectName(_fromUtf8("musicSeeker"))
        self.verticalLayout_3.addWidget(self.musicSeeker)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.trackName = QtGui.QLabel(self.centralwidget)
        self.trackName.setAlignment(QtCore.Qt.AlignCenter)
        self.trackName.setObjectName(_fromUtf8("trackName"))
        self.verticalLayout_2.addWidget(self.trackName)
        self.trackArtist = QtGui.QLabel(self.centralwidget)
        self.trackArtist.setAlignment(QtCore.Qt.AlignCenter)
        self.trackArtist.setObjectName(_fromUtf8("trackArtist"))
        self.verticalLayout_2.addWidget(self.trackArtist)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem4 = QtGui.QSpacerItem(125, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.loopButton = QtGui.QPushButton(self.centralwidget)
        self.loopButton.setObjectName(_fromUtf8("loopButton"))
        self.horizontalLayout_3.addWidget(self.loopButton)
        self.prevButton = QtGui.QPushButton(self.centralwidget)
        self.prevButton.setObjectName(_fromUtf8("prevButton"))
        self.horizontalLayout_3.addWidget(self.prevButton)
        self.playButton = QtGui.QPushButton(self.centralwidget)
        self.playButton.setObjectName(_fromUtf8("playButton"))
        self.horizontalLayout_3.addWidget(self.playButton)
        self.nextButton = QtGui.QPushButton(self.centralwidget)
        self.nextButton.setObjectName(_fromUtf8("nextButton"))
        self.horizontalLayout_3.addWidget(self.nextButton)
        self.randomButton = QtGui.QPushButton(self.centralwidget)
        self.randomButton.setObjectName(_fromUtf8("randomButton"))
        self.horizontalLayout_3.addWidget(self.randomButton)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.soundSeeker = QtGui.QSlider(self.centralwidget)
        self.soundSeeker.setMaximumSize(QtCore.QSize(16777215, 20))
        self.soundSeeker.setMaximum(100)
        self.soundSeeker.setProperty("value", 100)
        self.soundSeeker.setOrientation(QtCore.Qt.Horizontal)
        self.soundSeeker.setObjectName(_fromUtf8("soundSeeker"))
        self.horizontalLayout_3.addWidget(self.soundSeeker)
        spacerItem7 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.pushButton_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Luminous Player", None))
        self.searchEdit.setPlaceholderText(_translate("MainWindow", "Search music", None))
        self.userLogin.setText(_translate("MainWindow", "Connecting ...", None))
        self.label.setText(_translate("MainWindow", "My Library", None))
        __sortingEnabled = self.leftMenu.isSortingEnabled()
        self.leftMenu.setSortingEnabled(False)
        item = self.leftMenu.item(0)
        item.setText(_translate("MainWindow", "All Songs", None))
        item = self.leftMenu.item(1)
        item.setText(_translate("MainWindow", "Search Results", None))
        self.leftMenu.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("MainWindow", "Playlists", None))
        self.shuffleLibraryButton.setText(_translate("MainWindow", "Shuffle Library", None))
        self.pushButton.setText(_translate("MainWindow", "Download Selected", None))
        self.uploadMusicButton.setText(_translate("MainWindow", "Upload Music", None))
        self.allSongsTable.setSortingEnabled(True)
        item = self.allSongsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id", None))
        item = self.allSongsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.allSongsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Time", None))
        item = self.allSongsTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Artist", None))
        item = self.allSongsTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Album", None))
        item = self.allSongsTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Count", None))
        item = self.allSongsTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Rating", None))
        self.searchSongsTable.setSortingEnabled(True)
        item = self.searchSongsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id", None))
        item = self.searchSongsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.searchSongsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Time", None))
        item = self.searchSongsTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Artist", None))
        item = self.searchSongsTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Album", None))
        item = self.searchSongsTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Count", None))
        item = self.searchSongsTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Rating", None))
        self.trackName.setText(_translate("MainWindow", "Track Name", None))
        self.trackArtist.setText(_translate("MainWindow", "Artist", None))
        self.loopButton.setText(_translate("MainWindow", "Loop", None))
        self.prevButton.setText(_translate("MainWindow", "Prev", None))
        self.playButton.setText(_translate("MainWindow", "Play", None))
        self.nextButton.setText(_translate("MainWindow", "Next", None))
        self.randomButton.setText(_translate("MainWindow", "Random", None))
        self.pushButton_3.setText(_translate("MainWindow", "Rating Up", None))
        self.pushButton_4.setText(_translate("MainWindow", "Rating Down", None))

import luminous_rc
